[package]
name = "rustpython-ast"
version = "0.1.0"
authors = ["RustPython Team"]
edition = "2018"

[features]
default = ["constant-optimization", "fold"]
constant-optimization = ["fold"]
fold = []

[dependencies]
num-bigint = "0.4.0"
lazy_static = "1.4.0"
parking_lot = "0.11.1"
